### ISSUE TITLE
Training questions

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVNet#107]
Hi @dfulu , here are some questions from a Energy Forecasting company. They asked

1. How many images are used for the training process?

2. I've noticed that on the Eumetsat platform, cloud mask images appear to be delayed relative to the satellite images. How are these used in the forecasting process?

3. What is the frequency of updates? Is it every 15 minutes?

4. How many hours ahead do you forecast and with which granularity?

5. Do you possess any performance data specific to a concrete PV plant that you could share?
There is some open source data [here](https://huggingface.co/datasets/openclimatefix/uk_pv), but they are all quite small PV plants. 

@dfulu do you mind answering these? We could even add them to the Readme.md if we want

**Comment by jacobbieker** [comment]
For 2. cloud masks are not currently used at all. We just give the satellite imagery.
3. I believe its every half an hour? As the satellite data is delayed in production?
4. 8 hours at half-hourly resolution, being extended soon.
5. I don't think we have any specific PV plant data to share, since its all regional at the moment, even India is regional data instead.

**Comment by dfulu** [comment]
To add to what Jacob has said
1. We use 1.6 million training examples across the 317 GSPs. Thats selected over about 5 years (so ~500,000 different 5-minutely source satellite images). Each training example uses a history of 7 satellite images.
3. I thought the satellite data was only actually refreshed by the consumer once an hour. Hence we would get alternating 30-minute and 60-minute delays. Although I haven't looked at those delays since before summer.

**Comment by peterdudfield** [comment]
Could we make a PR and add this to the Readme.md please?

**Comment by peterdudfield** [comment]
@dfulu your probably the best person to update the Readme.md with these?

**Comment by peterdudfield** [comment]
Lets reflect on current Readme, and see what needs adding

**Comment by dfulu** [comment]
@peterdudfield I think we should close this. If we need it in the future, we could copy it to the github discussions page when needed
