### ISSUE TITLE
config - missing `number of batches` and `batch_output_dir`

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVNet#197]
Missing variables in configs.example
- batch_output_dir
- number_val_batches
- number_train_batches

This is needed for creating batches

Could we add these in?

**Comment by peterdudfield** [comment]
@AUdaltsova @Sukh-P

**Comment by Sukh-P** [comment]
Yeah good point, at the moment I think you can add them in when running the the save_batches script by adding + batch_output_dir="example_dir" for example when running the command but would be good to have this in the config example rather than needing to add that each time, maybe it's worth putting it [here](https://github.com/openclimatefix/PVNet/blob/main/configs.example/datamodule/streamed_batches.yaml) since this is the batch creation related config? Would need to change the save batches script slightly to refer to `config_dm` rather than `config` in places like [this](https://github.com/openclimatefix/PVNet/blob/main/scripts/save_batches.py#L113) if so
