### ISSUE TITLE
Upgrades to PVNet

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVNet#2]
- Add error bars on results - multiple Gaussian distribution
- Train with more NWP data (currently only 2 hours)
- Train with more data
- Check night time data
- Add more NWP channels, currently only _dswrf_

**Comment by peterdudfield** [comment]
https://app.neptune.ai/o/OpenClimateFix/org/predict-pv-yield/e/PRED-1231/charts
This is using 4 NWP variables and using 4 hours of NWP data

**Comment by peterdudfield** [comment]
upgrade forecast with NWP data -https://github.com/openclimatefix/nowcasting_forecast/issues/176

**Comment by dfulu** [comment]
The library has moved on quite a lot since this, so I'm going to close this as stale.  However, the current model addresses most of these:

> Add error bars on results - multiple Gaussian distribution

Currently underway via the quantile regression support #44 

> Train with more NWP data (currently only 2 hours)

Implemented. Using from -2 up to +8 hours for forecast

> Train with more data

Currently training on about 1,600,000 samples

> Check night time data

In production this is done inside the app

> Add more NWP channels, currently only dswrf

Currently we only use dswrf and t, so further exploration would be a good idea
