### ISSUE TITLE
Torch 2.5.0 crashes ocf-datapipes and fails testing

### ISSUE THREAD

**Issue by AUdaltsova** [openclimatefix/PVNet#263]
## Describe the bug
Getting this error from CI tests on a pull request:

```
    from torch.utils.data.datapipes.iter.combining import T_co, _ChildDataPipe, _ForkerIterDataPipe
E   ImportError: cannot import name 'T_co' from 'torch.utils.data.datapipes.iter.combining' (/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/torch/utils/data/datapipes/iter/combining.py)
```
CI is running with torch 2.5.0:
```
Requirement already satisfied: torch>=2.0.0 in /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages (from PVNet==3.0.59) (2.5.0)
```

As far as I can tell due to [this commint](https://github.com/pytorch/pytorch/commit/f1df13f023d747af73bb51c2740959b699aeba66) in torch 2.5.0 that refactored const `T_co` to `_T_co`, causing import to fail. We can refactor ocf-datapipes in the future or just put the requirement torch < 2.5.0 in PVNet for now

The last CI checks that ran before mine ran into this were [here](https://github.com/openclimatefix/PVNet/actions/runs/11213822437/job/31167636467?pr=259) and this run loaded `torch 2.4.1`:

```
Requirement already satisfied: torch>=2.0.0 in /opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages (from PVNet==3.0.58) (2.4.1)
```

**Comment by peterdudfield** [comment]
Yea I think its ok to pin for the moment. You can put an future issue in to upgrade pvnet to 2.5.0, and see if someone else wants to do it

**Comment by Sukh-P** [comment]
Thanks for investigating this! 

So my two cents is that these seems very much linked to the torch datapipes/ocf_datapipes and is only causing an issue in PVNet because of the current ocf_datapipes dependency which we plan to remove when ocf-data-sampler has feature parity with ocf_datapipes. Given this, would it be cleaner to pin torch in ocf_datapipes instead? In the short term it makes no difference as torch 2.4.1 would be chosen by the dependency resolver in PVNet but when ocf_datapipes is removed it means we don't have to change the torch pinning in PVNet again, happy with either way though

**Comment by AUdaltsova** [comment]
> Thanks for investigating this!
> 
> So my two cents is that these seems very much linked to the torch datapipes/ocf_datapipes and is only causing an issue in PVNet because of the current ocf_datapipes dependency which we plan to remove when ocf-data-sampler has feature parity with ocf_datapipes. Given this, would it be cleaner to pin torch in ocf_datapipes instead? In the short term it makes no difference as torch 2.4.1 would be chosen by the dependency resolver in PVNet but when ocf_datapipes is removed it means we don't have to change the torch pinning in PVNet again, happy with either way though

Yes very good point, just saw that this was a copy-over to support datapipes tooling specifically, so yes, probably best to pinon ocf_datapipes as shoud not affect dsampler
